apiVersion: v1
kind: Secret
metadata:
  name: kanban-api-discord
  namespace: kanban-api
type: Opaque
data:
  DISCORD_REPORT_BUG_ID: MTM3NjgyMzg1NTgwMDEyNzU1MA==
  DISCORD_REPORT_BUG_TOKEN: enZVbThvaFEyTXNIUllRc2lQVndUX0hIQkpQY2JsM1JVd19wNkpOTGd1RmJzdFZyQlhkblVnaGY3ZGNLYTJiMWxLOFo= 