// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Board is an object representing the database table.
type Board struct {
	ID          string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name        string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Alias       null.String `boil:"alias" json:"alias,omitempty" toml:"alias" yaml:"alias,omitempty"`
	Description null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	CreatedBy   null.String `boil:"created_by" json:"created_by,omitempty" toml:"created_by" yaml:"created_by,omitempty"`
	CreatedAt   time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt   null.Time   `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *boardR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L boardL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BoardColumns = struct {
	ID          string
	Name        string
	Alias       string
	Description string
	CreatedBy   string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   string
}{
	ID:          "id",
	Name:        "name",
	Alias:       "alias",
	Description: "description",
	CreatedBy:   "created_by",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
}

var BoardTableColumns = struct {
	ID          string
	Name        string
	Alias       string
	Description string
	CreatedBy   string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   string
}{
	ID:          "boards.id",
	Name:        "boards.name",
	Alias:       "boards.alias",
	Description: "boards.description",
	CreatedBy:   "boards.created_by",
	CreatedAt:   "boards.created_at",
	UpdatedAt:   "boards.updated_at",
	DeletedAt:   "boards.deleted_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) ILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" ILIKE ?", x)
}
func (w whereHelpernull_String) NILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT ILIKE ?", x)
}
func (w whereHelpernull_String) SIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" SIMILAR TO ?", x)
}
func (w whereHelpernull_String) NSIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var BoardWhere = struct {
	ID          whereHelperstring
	Name        whereHelperstring
	Alias       whereHelpernull_String
	Description whereHelpernull_String
	CreatedBy   whereHelpernull_String
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
	DeletedAt   whereHelpernull_Time
}{
	ID:          whereHelperstring{field: "\"boards\".\"id\""},
	Name:        whereHelperstring{field: "\"boards\".\"name\""},
	Alias:       whereHelpernull_String{field: "\"boards\".\"alias\""},
	Description: whereHelpernull_String{field: "\"boards\".\"description\""},
	CreatedBy:   whereHelpernull_String{field: "\"boards\".\"created_by\""},
	CreatedAt:   whereHelpertime_Time{field: "\"boards\".\"created_at\""},
	UpdatedAt:   whereHelpertime_Time{field: "\"boards\".\"updated_at\""},
	DeletedAt:   whereHelpernull_Time{field: "\"boards\".\"deleted_at\""},
}

// BoardRels is where relationship names are stored.
var BoardRels = struct {
	CreatedByUser          string
	Cards                  string
	Labels                 string
	Lists                  string
	PositionStatistics     string
	PositionValidationLogs string
	RebalanceEvents        string
	RebalanceJobs          string
}{
	CreatedByUser:          "CreatedByUser",
	Cards:                  "Cards",
	Labels:                 "Labels",
	Lists:                  "Lists",
	PositionStatistics:     "PositionStatistics",
	PositionValidationLogs: "PositionValidationLogs",
	RebalanceEvents:        "RebalanceEvents",
	RebalanceJobs:          "RebalanceJobs",
}

// boardR is where relationships are stored.
type boardR struct {
	CreatedByUser          *User                      `boil:"CreatedByUser" json:"CreatedByUser" toml:"CreatedByUser" yaml:"CreatedByUser"`
	Cards                  CardSlice                  `boil:"Cards" json:"Cards" toml:"Cards" yaml:"Cards"`
	Labels                 LabelSlice                 `boil:"Labels" json:"Labels" toml:"Labels" yaml:"Labels"`
	Lists                  ListSlice                  `boil:"Lists" json:"Lists" toml:"Lists" yaml:"Lists"`
	PositionStatistics     PositionStatisticSlice     `boil:"PositionStatistics" json:"PositionStatistics" toml:"PositionStatistics" yaml:"PositionStatistics"`
	PositionValidationLogs PositionValidationLogSlice `boil:"PositionValidationLogs" json:"PositionValidationLogs" toml:"PositionValidationLogs" yaml:"PositionValidationLogs"`
	RebalanceEvents        RebalanceEventSlice        `boil:"RebalanceEvents" json:"RebalanceEvents" toml:"RebalanceEvents" yaml:"RebalanceEvents"`
	RebalanceJobs          RebalanceJobSlice          `boil:"RebalanceJobs" json:"RebalanceJobs" toml:"RebalanceJobs" yaml:"RebalanceJobs"`
}

// NewStruct creates a new relationship struct
func (*boardR) NewStruct() *boardR {
	return &boardR{}
}

func (o *Board) GetCreatedByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetCreatedByUser()
}

func (r *boardR) GetCreatedByUser() *User {
	if r == nil {
		return nil
	}

	return r.CreatedByUser
}

func (o *Board) GetCards() CardSlice {
	if o == nil {
		return nil
	}

	return o.R.GetCards()
}

func (r *boardR) GetCards() CardSlice {
	if r == nil {
		return nil
	}

	return r.Cards
}

func (o *Board) GetLabels() LabelSlice {
	if o == nil {
		return nil
	}

	return o.R.GetLabels()
}

func (r *boardR) GetLabels() LabelSlice {
	if r == nil {
		return nil
	}

	return r.Labels
}

func (o *Board) GetLists() ListSlice {
	if o == nil {
		return nil
	}

	return o.R.GetLists()
}

func (r *boardR) GetLists() ListSlice {
	if r == nil {
		return nil
	}

	return r.Lists
}

func (o *Board) GetPositionStatistics() PositionStatisticSlice {
	if o == nil {
		return nil
	}

	return o.R.GetPositionStatistics()
}

func (r *boardR) GetPositionStatistics() PositionStatisticSlice {
	if r == nil {
		return nil
	}

	return r.PositionStatistics
}

func (o *Board) GetPositionValidationLogs() PositionValidationLogSlice {
	if o == nil {
		return nil
	}

	return o.R.GetPositionValidationLogs()
}

func (r *boardR) GetPositionValidationLogs() PositionValidationLogSlice {
	if r == nil {
		return nil
	}

	return r.PositionValidationLogs
}

func (o *Board) GetRebalanceEvents() RebalanceEventSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRebalanceEvents()
}

func (r *boardR) GetRebalanceEvents() RebalanceEventSlice {
	if r == nil {
		return nil
	}

	return r.RebalanceEvents
}

func (o *Board) GetRebalanceJobs() RebalanceJobSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRebalanceJobs()
}

func (r *boardR) GetRebalanceJobs() RebalanceJobSlice {
	if r == nil {
		return nil
	}

	return r.RebalanceJobs
}

// boardL is where Load methods for each relationship are stored.
type boardL struct{}

var (
	boardAllColumns            = []string{"id", "name", "alias", "description", "created_by", "created_at", "updated_at", "deleted_at"}
	boardColumnsWithoutDefault = []string{"name"}
	boardColumnsWithDefault    = []string{"id", "alias", "description", "created_by", "created_at", "updated_at", "deleted_at"}
	boardPrimaryKeyColumns     = []string{"id"}
	boardGeneratedColumns      = []string{}
)

type (
	// BoardSlice is an alias for a slice of pointers to Board.
	// This should almost always be used instead of []Board.
	BoardSlice []*Board
	// BoardHook is the signature for custom Board hook methods
	BoardHook func(context.Context, boil.ContextExecutor, *Board) error

	boardQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	boardType                 = reflect.TypeOf(&Board{})
	boardMapping              = queries.MakeStructMapping(boardType)
	boardPrimaryKeyMapping, _ = queries.BindMapping(boardType, boardMapping, boardPrimaryKeyColumns)
	boardInsertCacheMut       sync.RWMutex
	boardInsertCache          = make(map[string]insertCache)
	boardUpdateCacheMut       sync.RWMutex
	boardUpdateCache          = make(map[string]updateCache)
	boardUpsertCacheMut       sync.RWMutex
	boardUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var boardAfterSelectMu sync.Mutex
var boardAfterSelectHooks []BoardHook

var boardBeforeInsertMu sync.Mutex
var boardBeforeInsertHooks []BoardHook
var boardAfterInsertMu sync.Mutex
var boardAfterInsertHooks []BoardHook

var boardBeforeUpdateMu sync.Mutex
var boardBeforeUpdateHooks []BoardHook
var boardAfterUpdateMu sync.Mutex
var boardAfterUpdateHooks []BoardHook

var boardBeforeDeleteMu sync.Mutex
var boardBeforeDeleteHooks []BoardHook
var boardAfterDeleteMu sync.Mutex
var boardAfterDeleteHooks []BoardHook

var boardBeforeUpsertMu sync.Mutex
var boardBeforeUpsertHooks []BoardHook
var boardAfterUpsertMu sync.Mutex
var boardAfterUpsertHooks []BoardHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Board) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Board) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Board) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Board) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Board) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Board) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Board) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Board) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Board) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBoardHook registers your hook function for all future operations.
func AddBoardHook(hookPoint boil.HookPoint, boardHook BoardHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		boardAfterSelectMu.Lock()
		boardAfterSelectHooks = append(boardAfterSelectHooks, boardHook)
		boardAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		boardBeforeInsertMu.Lock()
		boardBeforeInsertHooks = append(boardBeforeInsertHooks, boardHook)
		boardBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		boardAfterInsertMu.Lock()
		boardAfterInsertHooks = append(boardAfterInsertHooks, boardHook)
		boardAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		boardBeforeUpdateMu.Lock()
		boardBeforeUpdateHooks = append(boardBeforeUpdateHooks, boardHook)
		boardBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		boardAfterUpdateMu.Lock()
		boardAfterUpdateHooks = append(boardAfterUpdateHooks, boardHook)
		boardAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		boardBeforeDeleteMu.Lock()
		boardBeforeDeleteHooks = append(boardBeforeDeleteHooks, boardHook)
		boardBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		boardAfterDeleteMu.Lock()
		boardAfterDeleteHooks = append(boardAfterDeleteHooks, boardHook)
		boardAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		boardBeforeUpsertMu.Lock()
		boardBeforeUpsertHooks = append(boardBeforeUpsertHooks, boardHook)
		boardBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		boardAfterUpsertMu.Lock()
		boardAfterUpsertHooks = append(boardAfterUpsertHooks, boardHook)
		boardAfterUpsertMu.Unlock()
	}
}

// One returns a single board record from the query.
func (q boardQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Board, error) {
	o := &Board{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for boards")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Board records from the query.
func (q boardQuery) All(ctx context.Context, exec boil.ContextExecutor) (BoardSlice, error) {
	var o []*Board

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to Board slice")
	}

	if len(boardAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Board records in the query.
func (q boardQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count boards rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q boardQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if boards exists")
	}

	return count > 0, nil
}

// CreatedByUser pointed to by the foreign key.
func (o *Board) CreatedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CreatedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Cards retrieves all the card's Cards with an executor.
func (o *Board) Cards(mods ...qm.QueryMod) cardQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"cards\".\"board_id\"=?", o.ID),
	)

	return Cards(queryMods...)
}

// Labels retrieves all the label's Labels with an executor.
func (o *Board) Labels(mods ...qm.QueryMod) labelQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"labels\".\"board_id\"=?", o.ID),
	)

	return Labels(queryMods...)
}

// Lists retrieves all the list's Lists with an executor.
func (o *Board) Lists(mods ...qm.QueryMod) listQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"lists\".\"board_id\"=?", o.ID),
	)

	return Lists(queryMods...)
}

// PositionStatistics retrieves all the position_statistic's PositionStatistics with an executor.
func (o *Board) PositionStatistics(mods ...qm.QueryMod) positionStatisticQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"position_statistics\".\"board_id\"=?", o.ID),
	)

	return PositionStatistics(queryMods...)
}

// PositionValidationLogs retrieves all the position_validation_log's PositionValidationLogs with an executor.
func (o *Board) PositionValidationLogs(mods ...qm.QueryMod) positionValidationLogQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"position_validation_log\".\"board_id\"=?", o.ID),
	)

	return PositionValidationLogs(queryMods...)
}

// RebalanceEvents retrieves all the rebalance_event's RebalanceEvents with an executor.
func (o *Board) RebalanceEvents(mods ...qm.QueryMod) rebalanceEventQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"rebalance_events\".\"board_id\"=?", o.ID),
	)

	return RebalanceEvents(queryMods...)
}

// RebalanceJobs retrieves all the rebalance_job's RebalanceJobs with an executor.
func (o *Board) RebalanceJobs(mods ...qm.QueryMod) rebalanceJobQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"rebalance_jobs\".\"board_id\"=?", o.ID),
	)

	return RebalanceJobs(queryMods...)
}

// LoadCreatedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (boardL) LoadCreatedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBoard interface{}, mods queries.Applicator) error {
	var slice []*Board
	var object *Board

	if singular {
		var ok bool
		object, ok = maybeBoard.(*Board)
		if !ok {
			object = new(Board)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBoard))
			}
		}
	} else {
		s, ok := maybeBoard.(*[]*Board)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBoard))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &boardR{}
		}
		if !queries.IsNil(object.CreatedBy) {
			args[object.CreatedBy] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &boardR{}
			}

			if !queries.IsNil(obj.CreatedBy) {
				args[obj.CreatedBy] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`users.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreatedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.CreatedByBoards = append(foreign.R.CreatedByBoards, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.CreatedBy, foreign.ID) {
				local.R.CreatedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.CreatedByBoards = append(foreign.R.CreatedByBoards, local)
				break
			}
		}
	}

	return nil
}

// LoadCards allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (boardL) LoadCards(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBoard interface{}, mods queries.Applicator) error {
	var slice []*Board
	var object *Board

	if singular {
		var ok bool
		object, ok = maybeBoard.(*Board)
		if !ok {
			object = new(Board)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBoard))
			}
		}
	} else {
		s, ok := maybeBoard.(*[]*Board)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBoard))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &boardR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &boardR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`cards`),
		qm.WhereIn(`cards.board_id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`cards.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load cards")
	}

	var resultSlice []*Card
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice cards")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on cards")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for cards")
	}

	if len(cardAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Cards = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &cardR{}
			}
			foreign.R.Board = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.BoardID {
				local.R.Cards = append(local.R.Cards, foreign)
				if foreign.R == nil {
					foreign.R = &cardR{}
				}
				foreign.R.Board = local
				break
			}
		}
	}

	return nil
}

// LoadLabels allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (boardL) LoadLabels(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBoard interface{}, mods queries.Applicator) error {
	var slice []*Board
	var object *Board

	if singular {
		var ok bool
		object, ok = maybeBoard.(*Board)
		if !ok {
			object = new(Board)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBoard))
			}
		}
	} else {
		s, ok := maybeBoard.(*[]*Board)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBoard))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &boardR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &boardR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`labels`),
		qm.WhereIn(`labels.board_id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`labels.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load labels")
	}

	var resultSlice []*Label
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice labels")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on labels")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for labels")
	}

	if len(labelAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Labels = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &labelR{}
			}
			foreign.R.Board = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.BoardID {
				local.R.Labels = append(local.R.Labels, foreign)
				if foreign.R == nil {
					foreign.R = &labelR{}
				}
				foreign.R.Board = local
				break
			}
		}
	}

	return nil
}

// LoadLists allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (boardL) LoadLists(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBoard interface{}, mods queries.Applicator) error {
	var slice []*Board
	var object *Board

	if singular {
		var ok bool
		object, ok = maybeBoard.(*Board)
		if !ok {
			object = new(Board)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBoard))
			}
		}
	} else {
		s, ok := maybeBoard.(*[]*Board)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBoard))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &boardR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &boardR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`lists`),
		qm.WhereIn(`lists.board_id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`lists.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load lists")
	}

	var resultSlice []*List
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice lists")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on lists")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for lists")
	}

	if len(listAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Lists = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &listR{}
			}
			foreign.R.Board = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.BoardID {
				local.R.Lists = append(local.R.Lists, foreign)
				if foreign.R == nil {
					foreign.R = &listR{}
				}
				foreign.R.Board = local
				break
			}
		}
	}

	return nil
}

// LoadPositionStatistics allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (boardL) LoadPositionStatistics(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBoard interface{}, mods queries.Applicator) error {
	var slice []*Board
	var object *Board

	if singular {
		var ok bool
		object, ok = maybeBoard.(*Board)
		if !ok {
			object = new(Board)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBoard))
			}
		}
	} else {
		s, ok := maybeBoard.(*[]*Board)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBoard))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &boardR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &boardR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`position_statistics`),
		qm.WhereIn(`position_statistics.board_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load position_statistics")
	}

	var resultSlice []*PositionStatistic
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice position_statistics")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on position_statistics")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for position_statistics")
	}

	if len(positionStatisticAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.PositionStatistics = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &positionStatisticR{}
			}
			foreign.R.Board = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.BoardID) {
				local.R.PositionStatistics = append(local.R.PositionStatistics, foreign)
				if foreign.R == nil {
					foreign.R = &positionStatisticR{}
				}
				foreign.R.Board = local
				break
			}
		}
	}

	return nil
}

// LoadPositionValidationLogs allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (boardL) LoadPositionValidationLogs(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBoard interface{}, mods queries.Applicator) error {
	var slice []*Board
	var object *Board

	if singular {
		var ok bool
		object, ok = maybeBoard.(*Board)
		if !ok {
			object = new(Board)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBoard))
			}
		}
	} else {
		s, ok := maybeBoard.(*[]*Board)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBoard))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &boardR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &boardR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`position_validation_log`),
		qm.WhereIn(`position_validation_log.board_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load position_validation_log")
	}

	var resultSlice []*PositionValidationLog
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice position_validation_log")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on position_validation_log")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for position_validation_log")
	}

	if len(positionValidationLogAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.PositionValidationLogs = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &positionValidationLogR{}
			}
			foreign.R.Board = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.BoardID) {
				local.R.PositionValidationLogs = append(local.R.PositionValidationLogs, foreign)
				if foreign.R == nil {
					foreign.R = &positionValidationLogR{}
				}
				foreign.R.Board = local
				break
			}
		}
	}

	return nil
}

// LoadRebalanceEvents allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (boardL) LoadRebalanceEvents(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBoard interface{}, mods queries.Applicator) error {
	var slice []*Board
	var object *Board

	if singular {
		var ok bool
		object, ok = maybeBoard.(*Board)
		if !ok {
			object = new(Board)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBoard))
			}
		}
	} else {
		s, ok := maybeBoard.(*[]*Board)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBoard))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &boardR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &boardR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`rebalance_events`),
		qm.WhereIn(`rebalance_events.board_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load rebalance_events")
	}

	var resultSlice []*RebalanceEvent
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice rebalance_events")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on rebalance_events")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for rebalance_events")
	}

	if len(rebalanceEventAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RebalanceEvents = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &rebalanceEventR{}
			}
			foreign.R.Board = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.BoardID) {
				local.R.RebalanceEvents = append(local.R.RebalanceEvents, foreign)
				if foreign.R == nil {
					foreign.R = &rebalanceEventR{}
				}
				foreign.R.Board = local
				break
			}
		}
	}

	return nil
}

// LoadRebalanceJobs allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (boardL) LoadRebalanceJobs(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBoard interface{}, mods queries.Applicator) error {
	var slice []*Board
	var object *Board

	if singular {
		var ok bool
		object, ok = maybeBoard.(*Board)
		if !ok {
			object = new(Board)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBoard))
			}
		}
	} else {
		s, ok := maybeBoard.(*[]*Board)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBoard)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBoard))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &boardR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &boardR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`rebalance_jobs`),
		qm.WhereIn(`rebalance_jobs.board_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load rebalance_jobs")
	}

	var resultSlice []*RebalanceJob
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice rebalance_jobs")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on rebalance_jobs")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for rebalance_jobs")
	}

	if len(rebalanceJobAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RebalanceJobs = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &rebalanceJobR{}
			}
			foreign.R.Board = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.BoardID) {
				local.R.RebalanceJobs = append(local.R.RebalanceJobs, foreign)
				if foreign.R == nil {
					foreign.R = &rebalanceJobR{}
				}
				foreign.R.Board = local
				break
			}
		}
	}

	return nil
}

// SetCreatedByUser of the board to the related item.
// Sets o.R.CreatedByUser to related.
// Adds o to related.R.CreatedByBoards.
func (o *Board) SetCreatedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"boards\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"created_by"}),
		strmangle.WhereClause("\"", "\"", 2, boardPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.CreatedBy, related.ID)
	if o.R == nil {
		o.R = &boardR{
			CreatedByUser: related,
		}
	} else {
		o.R.CreatedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			CreatedByBoards: BoardSlice{o},
		}
	} else {
		related.R.CreatedByBoards = append(related.R.CreatedByBoards, o)
	}

	return nil
}

// RemoveCreatedByUser relationship.
// Sets o.R.CreatedByUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Board) RemoveCreatedByUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.CreatedBy, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("created_by")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.CreatedByUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.CreatedByBoards {
		if queries.Equal(o.CreatedBy, ri.CreatedBy) {
			continue
		}

		ln := len(related.R.CreatedByBoards)
		if ln > 1 && i < ln-1 {
			related.R.CreatedByBoards[i] = related.R.CreatedByBoards[ln-1]
		}
		related.R.CreatedByBoards = related.R.CreatedByBoards[:ln-1]
		break
	}
	return nil
}

// AddCards adds the given related objects to the existing relationships
// of the board, optionally inserting them as new records.
// Appends related to o.R.Cards.
// Sets related.R.Board appropriately.
func (o *Board) AddCards(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Card) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.BoardID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"cards\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"board_id"}),
				strmangle.WhereClause("\"", "\"", 2, cardPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.BoardID = o.ID
		}
	}

	if o.R == nil {
		o.R = &boardR{
			Cards: related,
		}
	} else {
		o.R.Cards = append(o.R.Cards, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &cardR{
				Board: o,
			}
		} else {
			rel.R.Board = o
		}
	}
	return nil
}

// AddLabels adds the given related objects to the existing relationships
// of the board, optionally inserting them as new records.
// Appends related to o.R.Labels.
// Sets related.R.Board appropriately.
func (o *Board) AddLabels(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Label) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.BoardID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"labels\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"board_id"}),
				strmangle.WhereClause("\"", "\"", 2, labelPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.BoardID = o.ID
		}
	}

	if o.R == nil {
		o.R = &boardR{
			Labels: related,
		}
	} else {
		o.R.Labels = append(o.R.Labels, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &labelR{
				Board: o,
			}
		} else {
			rel.R.Board = o
		}
	}
	return nil
}

// AddLists adds the given related objects to the existing relationships
// of the board, optionally inserting them as new records.
// Appends related to o.R.Lists.
// Sets related.R.Board appropriately.
func (o *Board) AddLists(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*List) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.BoardID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"lists\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"board_id"}),
				strmangle.WhereClause("\"", "\"", 2, listPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.BoardID = o.ID
		}
	}

	if o.R == nil {
		o.R = &boardR{
			Lists: related,
		}
	} else {
		o.R.Lists = append(o.R.Lists, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &listR{
				Board: o,
			}
		} else {
			rel.R.Board = o
		}
	}
	return nil
}

// AddPositionStatistics adds the given related objects to the existing relationships
// of the board, optionally inserting them as new records.
// Appends related to o.R.PositionStatistics.
// Sets related.R.Board appropriately.
func (o *Board) AddPositionStatistics(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PositionStatistic) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.BoardID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"position_statistics\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"board_id"}),
				strmangle.WhereClause("\"", "\"", 2, positionStatisticPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.BoardID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &boardR{
			PositionStatistics: related,
		}
	} else {
		o.R.PositionStatistics = append(o.R.PositionStatistics, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &positionStatisticR{
				Board: o,
			}
		} else {
			rel.R.Board = o
		}
	}
	return nil
}

// SetPositionStatistics removes all previously related items of the
// board replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Board's PositionStatistics accordingly.
// Replaces o.R.PositionStatistics with related.
// Sets related.R.Board's PositionStatistics accordingly.
func (o *Board) SetPositionStatistics(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PositionStatistic) error {
	query := "update \"position_statistics\" set \"board_id\" = null where \"board_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.PositionStatistics {
			queries.SetScanner(&rel.BoardID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Board = nil
		}
		o.R.PositionStatistics = nil
	}

	return o.AddPositionStatistics(ctx, exec, insert, related...)
}

// RemovePositionStatistics relationships from objects passed in.
// Removes related items from R.PositionStatistics (uses pointer comparison, removal does not keep order)
// Sets related.R.Board.
func (o *Board) RemovePositionStatistics(ctx context.Context, exec boil.ContextExecutor, related ...*PositionStatistic) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.BoardID, nil)
		if rel.R != nil {
			rel.R.Board = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("board_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.PositionStatistics {
			if rel != ri {
				continue
			}

			ln := len(o.R.PositionStatistics)
			if ln > 1 && i < ln-1 {
				o.R.PositionStatistics[i] = o.R.PositionStatistics[ln-1]
			}
			o.R.PositionStatistics = o.R.PositionStatistics[:ln-1]
			break
		}
	}

	return nil
}

// AddPositionValidationLogs adds the given related objects to the existing relationships
// of the board, optionally inserting them as new records.
// Appends related to o.R.PositionValidationLogs.
// Sets related.R.Board appropriately.
func (o *Board) AddPositionValidationLogs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PositionValidationLog) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.BoardID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"position_validation_log\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"board_id"}),
				strmangle.WhereClause("\"", "\"", 2, positionValidationLogPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.BoardID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &boardR{
			PositionValidationLogs: related,
		}
	} else {
		o.R.PositionValidationLogs = append(o.R.PositionValidationLogs, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &positionValidationLogR{
				Board: o,
			}
		} else {
			rel.R.Board = o
		}
	}
	return nil
}

// SetPositionValidationLogs removes all previously related items of the
// board replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Board's PositionValidationLogs accordingly.
// Replaces o.R.PositionValidationLogs with related.
// Sets related.R.Board's PositionValidationLogs accordingly.
func (o *Board) SetPositionValidationLogs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PositionValidationLog) error {
	query := "update \"position_validation_log\" set \"board_id\" = null where \"board_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.PositionValidationLogs {
			queries.SetScanner(&rel.BoardID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Board = nil
		}
		o.R.PositionValidationLogs = nil
	}

	return o.AddPositionValidationLogs(ctx, exec, insert, related...)
}

// RemovePositionValidationLogs relationships from objects passed in.
// Removes related items from R.PositionValidationLogs (uses pointer comparison, removal does not keep order)
// Sets related.R.Board.
func (o *Board) RemovePositionValidationLogs(ctx context.Context, exec boil.ContextExecutor, related ...*PositionValidationLog) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.BoardID, nil)
		if rel.R != nil {
			rel.R.Board = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("board_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.PositionValidationLogs {
			if rel != ri {
				continue
			}

			ln := len(o.R.PositionValidationLogs)
			if ln > 1 && i < ln-1 {
				o.R.PositionValidationLogs[i] = o.R.PositionValidationLogs[ln-1]
			}
			o.R.PositionValidationLogs = o.R.PositionValidationLogs[:ln-1]
			break
		}
	}

	return nil
}

// AddRebalanceEvents adds the given related objects to the existing relationships
// of the board, optionally inserting them as new records.
// Appends related to o.R.RebalanceEvents.
// Sets related.R.Board appropriately.
func (o *Board) AddRebalanceEvents(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*RebalanceEvent) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.BoardID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"rebalance_events\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"board_id"}),
				strmangle.WhereClause("\"", "\"", 2, rebalanceEventPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.BoardID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &boardR{
			RebalanceEvents: related,
		}
	} else {
		o.R.RebalanceEvents = append(o.R.RebalanceEvents, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &rebalanceEventR{
				Board: o,
			}
		} else {
			rel.R.Board = o
		}
	}
	return nil
}

// SetRebalanceEvents removes all previously related items of the
// board replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Board's RebalanceEvents accordingly.
// Replaces o.R.RebalanceEvents with related.
// Sets related.R.Board's RebalanceEvents accordingly.
func (o *Board) SetRebalanceEvents(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*RebalanceEvent) error {
	query := "update \"rebalance_events\" set \"board_id\" = null where \"board_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.RebalanceEvents {
			queries.SetScanner(&rel.BoardID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Board = nil
		}
		o.R.RebalanceEvents = nil
	}

	return o.AddRebalanceEvents(ctx, exec, insert, related...)
}

// RemoveRebalanceEvents relationships from objects passed in.
// Removes related items from R.RebalanceEvents (uses pointer comparison, removal does not keep order)
// Sets related.R.Board.
func (o *Board) RemoveRebalanceEvents(ctx context.Context, exec boil.ContextExecutor, related ...*RebalanceEvent) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.BoardID, nil)
		if rel.R != nil {
			rel.R.Board = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("board_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.RebalanceEvents {
			if rel != ri {
				continue
			}

			ln := len(o.R.RebalanceEvents)
			if ln > 1 && i < ln-1 {
				o.R.RebalanceEvents[i] = o.R.RebalanceEvents[ln-1]
			}
			o.R.RebalanceEvents = o.R.RebalanceEvents[:ln-1]
			break
		}
	}

	return nil
}

// AddRebalanceJobs adds the given related objects to the existing relationships
// of the board, optionally inserting them as new records.
// Appends related to o.R.RebalanceJobs.
// Sets related.R.Board appropriately.
func (o *Board) AddRebalanceJobs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*RebalanceJob) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.BoardID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"rebalance_jobs\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"board_id"}),
				strmangle.WhereClause("\"", "\"", 2, rebalanceJobPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.BoardID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &boardR{
			RebalanceJobs: related,
		}
	} else {
		o.R.RebalanceJobs = append(o.R.RebalanceJobs, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &rebalanceJobR{
				Board: o,
			}
		} else {
			rel.R.Board = o
		}
	}
	return nil
}

// SetRebalanceJobs removes all previously related items of the
// board replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Board's RebalanceJobs accordingly.
// Replaces o.R.RebalanceJobs with related.
// Sets related.R.Board's RebalanceJobs accordingly.
func (o *Board) SetRebalanceJobs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*RebalanceJob) error {
	query := "update \"rebalance_jobs\" set \"board_id\" = null where \"board_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.RebalanceJobs {
			queries.SetScanner(&rel.BoardID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Board = nil
		}
		o.R.RebalanceJobs = nil
	}

	return o.AddRebalanceJobs(ctx, exec, insert, related...)
}

// RemoveRebalanceJobs relationships from objects passed in.
// Removes related items from R.RebalanceJobs (uses pointer comparison, removal does not keep order)
// Sets related.R.Board.
func (o *Board) RemoveRebalanceJobs(ctx context.Context, exec boil.ContextExecutor, related ...*RebalanceJob) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.BoardID, nil)
		if rel.R != nil {
			rel.R.Board = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("board_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.RebalanceJobs {
			if rel != ri {
				continue
			}

			ln := len(o.R.RebalanceJobs)
			if ln > 1 && i < ln-1 {
				o.R.RebalanceJobs[i] = o.R.RebalanceJobs[ln-1]
			}
			o.R.RebalanceJobs = o.R.RebalanceJobs[:ln-1]
			break
		}
	}

	return nil
}

// Boards retrieves all the records using an executor.
func Boards(mods ...qm.QueryMod) boardQuery {
	mods = append(mods, qm.From("\"boards\""), qmhelper.WhereIsNull("\"boards\".\"deleted_at\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"boards\".*"})
	}

	return boardQuery{q}
}

// FindBoard retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBoard(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Board, error) {
	boardObj := &Board{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"boards\" where \"id\"=$1 and \"deleted_at\" is null", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, boardObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from boards")
	}

	if err = boardObj.doAfterSelectHooks(ctx, exec); err != nil {
		return boardObj, err
	}

	return boardObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Board) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no boards provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(boardColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	boardInsertCacheMut.RLock()
	cache, cached := boardInsertCache[key]
	boardInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			boardAllColumns,
			boardColumnsWithDefault,
			boardColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(boardType, boardMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(boardType, boardMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"boards\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"boards\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into boards")
	}

	if !cached {
		boardInsertCacheMut.Lock()
		boardInsertCache[key] = cache
		boardInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Board.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Board) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	boardUpdateCacheMut.RLock()
	cache, cached := boardUpdateCache[key]
	boardUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			boardAllColumns,
			boardPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update boards, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"boards\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, boardPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(boardType, boardMapping, append(wl, boardPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update boards row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for boards")
	}

	if !cached {
		boardUpdateCacheMut.Lock()
		boardUpdateCache[key] = cache
		boardUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q boardQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for boards")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for boards")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BoardSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), boardPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"boards\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, boardPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in board slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all board")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Board) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no boards provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(boardColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	boardUpsertCacheMut.RLock()
	cache, cached := boardUpsertCache[key]
	boardUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			boardAllColumns,
			boardColumnsWithDefault,
			boardColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			boardAllColumns,
			boardPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert boards, could not build update column list")
		}

		ret := strmangle.SetComplement(boardAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(boardPrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert boards, could not build conflict column list")
			}

			conflict = make([]string, len(boardPrimaryKeyColumns))
			copy(conflict, boardPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"boards\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(boardType, boardMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(boardType, boardMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert boards")
	}

	if !cached {
		boardUpsertCacheMut.Lock()
		boardUpsertCache[key] = cache
		boardUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Board record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Board) Delete(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no Board provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), boardPrimaryKeyMapping)
		sql = "DELETE FROM \"boards\" WHERE \"id\"=$1"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"boards\" SET %s WHERE \"id\"=$2",
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		valueMapping, err := queries.BindMapping(boardType, boardMapping, append(wl, boardPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from boards")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for boards")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q boardQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no boardQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from boards")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for boards")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BoardSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(boardBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), boardPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM \"boards\" WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, boardPrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), boardPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"boards\" SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 2, boardPrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		args = append([]interface{}{currTime}, args...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from board slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for boards")
	}

	if len(boardAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Board) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBoard(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BoardSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BoardSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), boardPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"boards\".* FROM \"boards\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, boardPrimaryKeyColumns, len(*o)) +
		"and \"deleted_at\" is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in BoardSlice")
	}

	*o = slice

	return nil
}

// BoardExists checks if the Board row exists.
func BoardExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"boards\" where \"id\"=$1 and \"deleted_at\" is null limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if boards exists")
	}

	return exists, nil
}

// Exists checks if the Board row exists.
func (o *Board) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return BoardExists(ctx, exec, o.ID)
}
