// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	Boards         string
	CardActivities string
	Cards          string
	Labels         string
	Lists          string
	Roles          string
	Uploads        string
	Users          string
}{
	Boards:         "boards",
	CardActivities: "card_activities",
	Cards:          "cards",
	Labels:         "labels",
	Lists:          "lists",
	Roles:          "roles",
	Uploads:        "uploads",
	Users:          "users",
}
